/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description The process is up. Checks nothing else, so a database outage doesn't restart the API.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description The API can serve traffic: Postgres and object storage both answer.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Lectures */
        get: operations["list_lectures_v1_lectures_get"];
        put?: never;
        /** Create Lecture */
        post: operations["create_lecture_v1_lectures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lecture */
        get: operations["get_lecture_v1_lectures__lecture_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/complete-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description Idempotent: confirming an upload that's already confirmed returns the lecture unchanged.
         */
        post: operations["complete_upload_v1_lectures__lecture_id__complete_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Server-sent events: one JSON ProgressEvent per change, until the run finishes.
         */
        get: operations["events_v1_lectures__lecture_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Media
         * @description A presigned URL for playing the uploaded video. Browsers play MP4 (H.264/AAC) directly;
         *     other formats will need the HLS renditions planned for later.
         */
        get: operations["media_v1_lectures__lecture_id__media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notes */
        get: operations["notes_v1_lectures__lecture_id__notes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process
         * @description Idempotent: while a run is in progress, asking again returns that run.
         */
        post: operations["process_v1_lectures__lecture_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_lectures__lecture_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/slides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slides
         * @description Image URLs are presigned, so the browser loads slides straight from storage.
         */
        get: operations["slides_v1_lectures__lecture_id__slides_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_v1_lectures__lecture_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lectures/{lecture_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transcript */
        get: operations["transcript_v1_lectures__lecture_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Chapter */
        Chapter: {
            /** End S */
            end_s: number;
            /** Start S */
            start_s: number;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** Concept */
        Concept: {
            /** At S */
            at_s: number;
            /** Definition */
            definition: string;
            /** Term */
            term: string;
        };
        /** Formula */
        Formula: {
            /** At S */
            at_s: number;
            /** Latex */
            latex: string;
            /** Meaning */
            meaning: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LectureCreate */
        LectureCreate: {
            /** Attribution */
            attribution?: string | null;
            /**
             * Content Type
             * @example video/mp4
             */
            content_type: string;
            /**
             * Filename
             * @example 6.006-lecture-01.mp4
             */
            filename: string;
            /**
             * Licence
             * @example CC BY-NC-SA 4.0
             */
            licence?: string | null;
            /** Title */
            title: string;
        };
        /** LectureCreated */
        LectureCreated: {
            lecture: components["schemas"]["LectureOut"];
            upload: components["schemas"]["UploadTarget"];
        };
        /** LectureOut */
        LectureOut: {
            /** Attribution */
            attribution: string | null;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration S */
            duration_s: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Licence */
            licence: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            /** Source Filename */
            source_filename: string;
            status: components["schemas"]["LectureStatus"];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LectureStatus
         * @enum {string}
         */
        LectureStatus: "awaiting_upload" | "uploaded" | "processing" | "ready" | "failed";
        /**
         * MediaOut
         * @description Where the browser plays the lecture from: a presigned URL straight to storage.
         */
        MediaOut: {
            /** Content Type */
            content_type: string;
            /** Expires In S */
            expires_in_s: number;
            /** Url */
            url: string;
        };
        /** NotesOut */
        NotesOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Model */
            model: string;
            notes: components["schemas"]["StudyNotes"];
            /** Run Id */
            run_id: string | null;
        };
        /** Progress */
        Progress: {
            /**
             * Done
             * @default []
             */
            done: components["schemas"]["StageInfo"][];
            /** Error */
            error?: string | null;
            /**
             * Running
             * @default []
             */
            running: string[];
            /**
             * Status
             * @default running
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed";
        };
        /**
         * ProgressEvent
         * @description One server-sent event: the lecture's status and its latest run's progress.
         */
        ProgressEvent: {
            lecture_status: components["schemas"]["LectureStatus"];
            progress: components["schemas"]["Progress"] | null;
            /** Run Id */
            run_id: string | null;
        };
        /** QuizQuestion */
        QuizQuestion: {
            /** Answer */
            answer: string;
            /** At S */
            at_s: number;
            /** Question */
            question: string;
        };
        /** RunOut */
        RunOut: {
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lecture Id
             * Format: uuid
             */
            lecture_id: string;
            /** Llm Usage */
            llm_usage: {
                [key: string]: unknown;
            } | null;
            /** Stages */
            stages: components["schemas"]["StageInfo"][];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "running" | "succeeded" | "failed";
        /** SlideOut */
        SlideOut: {
            /** Code */
            code: string;
            /** Figure Description */
            figure_description: string;
            /** First Seen S */
            first_seen_s: number;
            /** Image Url */
            image_url: string;
            /** Latex */
            latex: string[];
            /** Slide Id */
            slide_id: number;
            /** Spans */
            spans: components["schemas"]["TimeSpan"][];
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** StageInfo */
        StageInfo: {
            /** Cached */
            cached: boolean;
            /** Seconds */
            seconds: number;
            /** Stage */
            stage: string;
        };
        /** StudyNotes */
        StudyNotes: {
            /** Chapters */
            chapters: components["schemas"]["Chapter"][];
            /** Concepts */
            concepts: components["schemas"]["Concept"][];
            /** Formulas */
            formulas: components["schemas"]["Formula"][];
            /** Quiz */
            quiz: components["schemas"]["QuizQuestion"][];
            /** Tldr */
            tldr: string;
        };
        /** TimeSpan */
        TimeSpan: {
            /** End S */
            end_s: number;
            /** Start S */
            start_s: number;
        };
        /** TimelineSegmentOut */
        TimelineSegmentOut: {
            /** End S */
            end_s: number;
            /** Segment Id */
            segment_id: string;
            /** Slide Id */
            slide_id: number | null;
            /** Start S */
            start_s: number;
            /** Transcript */
            transcript: string;
        };
        /** TranscriptLineOut */
        TranscriptLineOut: {
            /** End S */
            end_s: number;
            /** Index */
            index: number;
            /** Start S */
            start_s: number;
            /** Text */
            text: string;
        };
        /**
         * UploadTarget
         * @description Send the file with `method` to `url`, including `headers` exactly as given.
         */
        UploadTarget: {
            /** Expires In S */
            expires_in_s: number;
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /**
             * Method
             * @default PUT
             * @constant
             */
            method: "PUT";
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_lectures_v1_lectures_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LectureOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lecture_v1_lectures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LectureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LectureCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lecture_v1_lectures__lecture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LectureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_v1_lectures__lecture_id__complete_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LectureOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_v1_lectures__lecture_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent events. Each `data:` line is a ProgressEvent as JSON. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_v1_lectures__lecture_id__media_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notes_v1_lectures__lecture_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_v1_lectures__lecture_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_lectures__lecture_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slides_v1_lectures__lecture_id__slides_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlideOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_v1_lectures__lecture_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineSegmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcript_v1_lectures__lecture_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lecture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptLineOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
