"""courses

Revision ID: 778608773f12
Revises: 968de42cae62
Create Date: 2026-09-29 09:39:27.633255

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "778608773f12"
down_revision: str | Sequence[str] | None = "968de42cae62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    op.add_column("lectures", sa.Column("course_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_lectures_course_id"), "lectures", ["course_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_lectures_course_id_courses"),
        "lectures",
        "courses",
        ["course_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("qa_threads", sa.Column("course_id", sa.Uuid(), nullable=True))
    op.alter_column("qa_threads", "lecture_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(op.f("ix_qa_threads_course_id"), "qa_threads", ["course_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_qa_threads_course_id_courses"),
        "qa_threads",
        "courses",
        ["course_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    # Autogenerate doesn't detect check constraints: a thread is about a lecture or a course.
    op.create_check_constraint(
        op.f("ck_qa_threads_one_scope"), "qa_threads", "num_nonnulls(lecture_id, course_id) = 1"
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_qa_threads_one_scope"), "qa_threads", type_="check")
    # Course threads can't survive losing the course columns.
    op.execute("DELETE FROM qa_threads WHERE lecture_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_qa_threads_course_id_courses"), "qa_threads", type_="foreignkey")
    op.drop_index(op.f("ix_qa_threads_course_id"), table_name="qa_threads")
    op.alter_column("qa_threads", "lecture_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("qa_threads", "course_id")
    op.drop_constraint(op.f("fk_lectures_course_id_courses"), "lectures", type_="foreignkey")
    op.drop_index(op.f("ix_lectures_course_id"), table_name="lectures")
    op.drop_column("lectures", "course_id")
    op.drop_table("courses")
    # ### end Alembic commands ###
