"""slide reader

Revision ID: bc70cc114811
Revises: 6f5544995e69
Create Date: 2026-09-29 17:18:21.368872

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc70cc114811"
down_revision: str | Sequence[str] | None = "6f5544995e69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slides", sa.Column("reader", sa.String(length=8), server_default="vlm", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slides", "reader")
    # ### end Alembic commands ###
