"""usage events for quotas

Revision ID: dc4d01cd56d0
Revises: 935e641a9791
Create Date: 2026-10-02 06:37:51.870802

The quotas count these from now on. The table starts empty, so what was used earlier on the day
it's applied isn't counted that day.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc4d01cd56d0"
down_revision: str | Sequence[str] | None = "935e641a9791"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("upload", "question", "llm", name="usagekind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("cost_usd", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_usage_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    op.create_index(
        "ix_usage_events_kind_created", "usage_events", ["kind", "created_at"], unique=False
    )
    op.create_index(op.f("ix_usage_events_user_id"), "usage_events", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_events_user_id"), table_name="usage_events")
    op.drop_index("ix_usage_events_kind_created", table_name="usage_events")
    op.drop_table("usage_events")
    # ### end Alembic commands ###
