"""users and ownership

Revision ID: 935e641a9791
Revises: bc70cc114811
Create Date: 2026-09-30 23:26:35.592387

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "935e641a9791"
down_revision: str | Sequence[str] | None = "bc70cc114811"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("subject", name=op.f("uq_users_subject")),
    )
    op.add_column("courses", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.add_column(
        "courses",
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="visibility", native_enum=False, length=16),
            server_default="private",
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_courses_owner_id"), "courses", ["owner_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_courses_owner_id_users"),
        "courses",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("lectures", sa.Column("owner_id", sa.Uuid(), nullable=True))
    op.add_column(
        "lectures",
        sa.Column(
            "visibility",
            sa.Enum("public", "private", name="visibility", native_enum=False, length=16),
            server_default="private",
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_lectures_owner_id"), "lectures", ["owner_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_lectures_owner_id_users"),
        "lectures",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("qa_threads", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_qa_threads_user_id"), "qa_threads", ["user_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_qa_threads_user_id_users"),
        "qa_threads",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
    # Everything so far was added without sign-in: the demo lectures and courses, public.
    op.execute("UPDATE lectures SET visibility = 'public'")
    op.execute("UPDATE courses SET visibility = 'public'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_qa_threads_user_id_users"), "qa_threads", type_="foreignkey")
    op.drop_index(op.f("ix_qa_threads_user_id"), table_name="qa_threads")
    op.drop_column("qa_threads", "user_id")
    op.drop_constraint(op.f("fk_lectures_owner_id_users"), "lectures", type_="foreignkey")
    op.drop_index(op.f("ix_lectures_owner_id"), table_name="lectures")
    op.drop_column("lectures", "visibility")
    op.drop_column("lectures", "owner_id")
    op.drop_constraint(op.f("fk_courses_owner_id_users"), "courses", type_="foreignkey")
    op.drop_index(op.f("ix_courses_owner_id"), table_name="courses")
    op.drop_column("courses", "visibility")
    op.drop_column("courses", "owner_id")
    op.drop_table("users")
    # ### end Alembic commands ###
