"""create lectures

Revision ID: 0fce27a40a06
Revises:
Create Date: 2026-09-27 17:40:03.182572

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fce27a40a06"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lectures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "awaiting_upload",
                "uploaded",
                "processing",
                "ready",
                "failed",
                name="lecturestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_key", sa.String(length=512), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("duration_s", sa.Double(), nullable=True),
        sa.Column("licence", sa.String(length=100), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lectures")),
    )
    op.create_index(op.f("ix_lectures_content_hash"), "lectures", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lectures_content_hash"), table_name="lectures")
    op.drop_table("lectures")
    # ### end Alembic commands ###
