"""Database schema. Change it here, then run `make revision m="..."` to generate a migration."""

import uuid
from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Deterministic constraint names keep autogenerated migrations stable.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class LectureStatus(StrEnum):
    AWAITING_UPLOAD = "awaiting_upload"
    UPLOADED = "uploaded"
    PROCESSING = "processing"
    READY = "ready"
    FAILED = "failed"


def _enum_values(enum_cls: type[StrEnum]) -> list[str]:
    return [member.value for member in enum_cls]


class Visibility(StrEnum):
    PUBLIC = "public"  # anyone can read and search it, signed in or not
    PRIVATE = "private"  # its owner and admins only


def _visibility() -> Enum:
    return Enum(Visibility, native_enum=False, length=16, values_callable=_enum_values)


class User(Base):
    """Someone signed in through the issuer (docs/adr/0009), added on their first request."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    # The issuer's id for them: the token's `sub` (Clerk's user_...).
    subject: Mapped[str] = mapped_column(String(255), unique=True)
    email: Mapped[str | None] = mapped_column(String(320))
    name: Mapped[str | None] = mapped_column(String(200))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Course(Base):
    """A group of lectures that search and Q&A can span."""

    __tablename__ = "courses"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    title: Mapped[str] = mapped_column(String(300))
    description: Mapped[str | None] = mapped_column(Text)
    # No owner: made without sign-in (the local stack's demo courses).
    owner_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), index=True
    )
    visibility: Mapped[Visibility] = mapped_column(
        _visibility(), server_default=Visibility.PRIVATE.value
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Lecture(Base):
    __tablename__ = "lectures"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    title: Mapped[str] = mapped_column(String(300))
    # A lecture belongs to at most one course. Deleting the course keeps the lecture.
    course_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("courses.id", ondelete="SET NULL"), index=True
    )
    # Who uploaded it; none for lectures added without sign-in (the demo lectures).
    owner_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), index=True
    )
    visibility: Mapped[Visibility] = mapped_column(
        _visibility(), server_default=Visibility.PRIVATE.value
    )
    # Stored as VARCHAR rather than a native enum, so adding a status needs no ALTER TYPE.
    status: Mapped[LectureStatus] = mapped_column(
        Enum(LectureStatus, native_enum=False, length=32, values_callable=_enum_values),
        default=LectureStatus.AWAITING_UPLOAD,
    )
    source_key: Mapped[str] = mapped_column(String(512))
    source_filename: Mapped[str] = mapped_column(String(255))
    content_type: Mapped[str] = mapped_column(String(100))
    size_bytes: Mapped[int | None] = mapped_column(BigInteger)
    # SHA-256 of the source file, computed at ingest and used to dedupe re-uploads.
    content_hash: Mapped[str | None] = mapped_column(String(64), index=True)
    duration_s: Mapped[float | None]
    licence: Mapped[str | None] = mapped_column(String(100))
    attribution: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class RunStatus(StrEnum):
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class PipelineRun(Base):
    """One processing run of a lecture: a ProcessLecture workflow execution."""

    __tablename__ = "pipeline_runs"
    __table_args__ = (
        # At most one running run per lecture, even if two process requests race.
        Index(
            "uq_pipeline_runs_one_running",
            "lecture_id",
            unique=True,
            postgresql_where=text("status = 'running'"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    lecture_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("lectures.id", ondelete="CASCADE"), index=True
    )
    workflow_id: Mapped[str] = mapped_column(String(100))
    status: Mapped[RunStatus] = mapped_column(
        Enum(RunStatus, native_enum=False, length=16, values_callable=_enum_values),
        default=RunStatus.RUNNING,
    )
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    error: Mapped[str | None] = mapped_column(Text)
    # [{stage, seconds, cached}], in completion order.
    stages: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, default=list)
    llm_usage: Mapped[dict[str, Any] | None] = mapped_column(JSONB)


# Results of the latest successful run. Each run replaces a lecture's rows in one transaction.


class TranscriptSegmentRow(Base):
    __tablename__ = "transcript_segments"

    lecture_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("lectures.id", ondelete="CASCADE"), primary_key=True
    )
    index: Mapped[int] = mapped_column(Integer, primary_key=True)
    start_s: Mapped[float]
    end_s: Mapped[float]
    text: Mapped[str] = mapped_column(Text)
    # [{start_s, end_s, text, probability}]
    words: Mapped[list[dict[str, Any]]] = mapped_column(JSONB)


class SlideRow(Base):
    __tablename__ = "slides"

    lecture_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("lectures.id", ondelete="CASCADE"), primary_key=True
    )
    slide_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    image_key: Mapped[str] = mapped_column(String(512))
    first_seen_s: Mapped[float]
    title: Mapped[str] = mapped_column(Text)
    text: Mapped[str] = mapped_column(Text)
    figure_description: Mapped[str] = mapped_column(Text)
    latex: Mapped[list[str]] = mapped_column(JSONB)
    code: Mapped[str] = mapped_column(Text)
    # Who read the slide: the vision LLM ("vlm") or OCR alone ("ocr").
    reader: Mapped[Literal["vlm", "ocr"]] = mapped_column(String(8), server_default="vlm")
    # [{start_s, end_s}]: every stretch of the video during which this is the current slide.
    spans: Mapped[list[dict[str, float]]] = mapped_column(JSONB)


class TimelineSegmentRow(Base):
    __tablename__ = "timeline_segments"

    lecture_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("lectures.id", ondelete="CASCADE"), primary_key=True
    )
    segment_id: Mapped[str] = mapped_column(String(16), primary_key=True)
    index: Mapped[int] = mapped_column(Integer)
    start_s: Mapped[float]
    end_s: Mapped[float]
    transcript: Mapped[str] = mapped_column(Text)
    slide_id: Mapped[int | None] = mapped_column(Integer)


class SummaryRow(Base):
    """Generated summaries of a lecture, by kind. So far one kind: "study_notes"."""

    __tablename__ = "summaries"

    lecture_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("lectures.id", ondelete="CASCADE"), primary_key=True
    )
    kind: Mapped[str] = mapped_column(String(32), primary_key=True)
    run_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("pipeline_runs.id", ondelete="SET NULL")
    )
    content: Mapped[dict[str, Any]] = mapped_column(JSONB)
    model: Mapped[str] = mapped_column(String(100))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


# Q&A


class QAThread(Base):
    """A conversation about one lecture, or about all of a course's lectures."""

    __tablename__ = "qa_threads"
    __table_args__ = (CheckConstraint("num_nonnulls(lecture_id, course_id) = 1", name="one_scope"),)

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    lecture_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("lectures.id", ondelete="CASCADE"), index=True
    )
    course_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("courses.id", ondelete="CASCADE"), index=True
    )
    # Who asked; none without sign-in. Threads are private to their user.
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    # The first question, shortened.
    title: Mapped[str] = mapped_column(String(200))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class MessageRole(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"


class QAMessage(Base):
    """A question, or the answer to it. Answers record what was retrieved and cited, and what
    they cost."""

    __tablename__ = "qa_messages"
    __table_args__ = (Index("ix_qa_messages_thread_created", "thread_id", "created_at"),)

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    thread_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("qa_threads.id", ondelete="CASCADE"))
    role: Mapped[MessageRole] = mapped_column(
        Enum(MessageRole, native_enum=False, length=16, values_callable=_enum_values)
    )
    content: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    # Answers only. The question as searched, when a follow-up was rewritten to stand alone.
    search_query: Mapped[str | None] = mapped_column(Text)
    # [{lecture_id, segment_id, start_s, end_s, slide_title, chapter, score}]
    sources: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB)
    # [{label, at_s, segment_id, valid}]
    citations: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB)
    model: Mapped[str | None] = mapped_column(String(100))
    # {requests, input_tokens, output_tokens}
    usage: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    first_token_ms: Mapped[int | None] = mapped_column(Integer)
    total_ms: Mapped[int | None] = mapped_column(Integer)
    # Why the answer failed, as shown to the reader; the details are in the API's log.
    error: Mapped[str | None] = mapped_column(Text)


class Rating(StrEnum):
    UP = "up"
    DOWN = "down"


class Feedback(Base):
    """A reader's rating of an answer. Rating it again replaces the earlier rating."""

    __tablename__ = "feedback"

    message_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("qa_messages.id", ondelete="CASCADE"), primary_key=True
    )
    rating: Mapped[Rating] = mapped_column(
        Enum(Rating, native_enum=False, length=8, values_callable=_enum_values)
    )
    reason: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class EvalRun(Base):
    """One run of an eval suite (evals/): what was measured, on which data, at which commit."""

    __tablename__ = "eval_runs"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    suite: Mapped[str] = mapped_column(String(32), index=True)
    # The dataset file, and a hash of its contents as its version.
    dataset: Mapped[str] = mapped_column(String(200))
    dataset_sha256: Mapped[str] = mapped_column(String(64))
    lecture_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("lectures.id", ondelete="SET NULL")
    )
    # The commit the evals ran at; "-dirty" when the working tree had changes.
    git_sha: Mapped[str | None] = mapped_column(String(48))
    # Models, modes and settings the run used.
    config: Mapped[dict[str, Any]] = mapped_column(JSONB)
    # {metric: value}
    metrics: Mapped[dict[str, float]] = mapped_column(JSONB)
    # Against evals/thresholds.json; None when the suite has no thresholds.
    passed: Mapped[bool | None]
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
